version: "3.9"

services:
  app:
    build: .
    container_name: next-app
    ports:
      - "3002:3000"
    environment:
      DATABASE_URL: postgresql://postgres:postgres@db:5432/mydb
      NODE_ENV: production
    depends_on:
      - db

  db:
    image: postgres:16-alpine
    container_name: postgres-db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: mydb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
